### ISSUE TITLE
Exit 0 when Salesforce API Error

### ISSUE THREAD

**Issue by to-lz1** [mikoto2000/embulk-input-salesforce_bulk#14]
Hello, we are considering to use this plugin in our data infrastructure.

Trying to use this plugin, we found that our Embulk task continue to run, even if we failed to login to our Salesforce account.

as @irotoris mentioned in this PR, it's because this plugin catches the error, and doesn't propagate it.
https://github.com/mikoto2000/embulk-input-salesforce_bulk/pull/13

I think PR above is sufficient to fix this issue, and we really appreciate if you notice and make any response. Thank you.

**Comment by mikoto2000** [comment]
Sorry for the late response.
Merged and released now.
