### ISSUE TITLE
Support for TLS 1.1+

### ISSUE THREAD

**Issue by bcipolli** [mikoto2000/embulk-input-salesforce_bulk#7]
Salesforce is turning off TLS 1.0 support:
https://help.salesforce.com/HTViewSolution?id=000221207

Our sys adminsitrator told me that the ETL process seems to be using TLS 1.0. We are using this input plugin.

Any ideas how to get the client to use TLS 1.1+?

**Comment by mikoto2000** [comment]
I activate "Require TLS 1.1 or higher for HTTPS connections" on Salesforce developer edition and executed this plugin.

![image](https://user-images.githubusercontent.com/345832/28256500-015708e8-6afe-11e7-983d-03fed568b0e8.png)
![image](https://user-images.githubusercontent.com/345832/28256594-f30e7cd4-6afe-11e7-9d25-81748d12cae4.png)

I think this plugin using TLS 1.1+.
Are you having trouble with your environment?

My environment:
- OS: Windows 10 Pro
- Java: 1.8.0_131

**Comment by bcipolli** [comment]
Ok, that's great to hear. I will follow up with our sys administrator to see what our configuration is. P.S. My environment is OSX 10.12.5, Java 1.8.0_91-b14
